### ISSUE TITLE
Incorrect redirect when not using urlRewrite

### ISSUE THREAD

**Issue by aschempp** [contao/core#7666]
The language prefix is added before the script under following conditions:

- Disable urlRewrite 
- Enable language in URL
- Go to http://example.com/index.php/en

The trailing slash for the language is missing, therefore the system is trying to redirect to https://example.com/en/index.php/en, where the language prefix is before the index.php script.

**Comment by leofeyer** [comment]
Fixed in d23658944963b3cc146649ab2339258ac151c927.

**Comment by aschempp** [comment]
The problem persists if you add just one character after the URL.

**Comment by leofeyer** [comment]
That's correct, because "e" is not a valid locale.

**Comment by aschempp** [comment]
It actually happens for anything (http://example.com/index.php/test). Shouldn't that trigger the Contao 404 page?

**Comment by aschempp** [comment]
Actually, it redirects incorrectly which is definitely a bug.

**Comment by leofeyer** [comment]
What exactly do you mean? Is the language added before the `index.php` fragment in your case?

**Comment by aschempp** [comment]
Exactly. If I point to http://example.com/index.php/test I'm being redirected to http://example.com/en/index.php/test

**Comment by leofeyer** [comment]
Ok, that's wrong indeed.

**Comment by leofeyer** [comment]
Fixed in 4d3ef21fdd1a98d8443c2fa55a3c145c7929dedb.
