### ISSUE TITLE
Minify the markup must not remove all spaces, but collapse instead

### ISSUE THREAD

**Issue by Ruudt** [contao/core#7734]
Contao settings allow to "Minify the markup". This removes whitespaces between HTML elements. But that alters the structure of the document. Therefore Contao should collapse whitespaces instead of removing them altogether.

In the examples below decrease the width of the "Result" pane until the menu doesn't fit. Because the HTML changed the results are different between the two examples. You can see the difference instantly because the spaces are visible in the first example. Tested with Chrome and Firefox.

Example with whitespaces:
https://jsfiddle.net/nkqwbfyo/

Example without whitespaces:
https://jsfiddle.net/nkqwbfyo/1/

**Comment by discordier** [comment]
Just also ran into a similar issue with the file picker.
Filename is: `foo<space><space>bar.jpg`
The picker produces then:
```html
<input value="foo<space>bar.jpg"
```
Note the missing second space.
We therefore must not strip consecutive spaces in html attributes as well.

**Comment by beaniemonk** [comment]
I was about to submit a sort-of-related ticket when I saw this one, so I hope you don't mind me piggybacking off it instead...

This is actually one of my favorite things about the HTML minifier :) It makes inline-block grids/layouts a breeze, and avoids having to use hacky workarounds like these:
https://css-tricks.com/fighting-the-space-between-inline-block-elements/

However, the minifier also tries to preserve white-space between inline HTML tags (which I agree is good) by using the following regex pattern: ```'/>\n<(a|input|select|span)/' => '> <$1'```

The problem I run into with the above is, in addition to preserving the white-space between tags like ```<a>```, ```<abbr>``` and ```<audio>``` (which again, I agree is good), it also preserves them for tags that start with 'a' but are actually *block* elements -- namely ```<address>```, ```<article>``` and ```<aside>```. This results in inconsistent behavior, and I end up having to avoid these elements in my custom templates so those extra spaces don't break stuff. And that's a shame, because all 3 very valuable, semantic elements.

So I wanted to propose one of two things:

1. Adjust the snippet above to only match *inline* elements that start with 'a', for example: ```'/>\n<(a(\b|bbr|udio)|input|select|span)/' => '> <$1'```

2. Move $arrReplace -- used in Template::minifyHtml() -- to a global configuration array so that we can customize it to our needs. (Otherwise this change will BC break several of our sites if we update them).

**Note:** For use cases like the one Ruud's describing, setting the element to 'display: inline-block' instead of 'display: inline' will allow them to wrap as intended which would fix his issue (e.g. https://jsfiddle.net/r0r3yxoq/). It won't re-add spaces between them, but it's more common for front-end folks to not want those spaces there, IMHO.

Thanks!

**Comment by leofeyer** [comment]
Maybe we should discuss what to change in one of the next Mumble calls.

> Adjust the snippet above to only match *inline* elements that start with 'a', for example: ```'/>\n<(a(\b|bbr|udio)|input|select|span)/' => '> <$1'```

I agree, however, it seems we should apply it to all inline elements instead of just a handful.

**Comment by fritzmg** [comment]
Just to expand on Ruudt's example: there is also a common way to make the items of horizontal menus distribute evenly spaced (even when their individual width is different) by using a combination of `text-align:justify;` and `display:inline-block;`. However, this does not work with minified HTML.

See https://jsfiddle.net/311rd37j/ vs. https://jsfiddle.net/7sc3Lptf/

Though I don't know how this could be solved other than not minifying the HTML at all?

**Comment by fritzmg** [comment]
@Ruudt where did your comment go? :)

> fritzmg, they can collapse all whitespaces like I suggested. See https://jsfiddle.net/7sc3Lptf/1/

ah, I didn't know what you mean at first. You mean all whitespace should be collapsed to one space between all tags always.

**Comment by leofeyer** [comment]
As discussed on Mumble on July 16th, we should only strip leading whitespace characters like the Google pagespeed module does. And we should apply the above fix to all inline elements.

**Comment by discordier** [comment]
Also trailing whitespace (only space and tab) and consecutive line breaks.

**Comment by leofeyer** [comment]
Fixed in 8e1a1d0a054f2939cfbf0687f009ad4f66df7d89. Can you please check if the changes work for you?

**Comment by ausi** [comment]
It breaks code like this:

```html
<pre>
line 1

line 3
</pre>
```

The empty line would be removed, which is wrong IMO.

But leading and trailing whitespace doesn’t always get removed:

```html
<div>foo                     
                    bar</div>
```

All three lines of the following script get broken:

```html
<script>
func('tag[attr] tag');
var foo = a + ': ' + b;
var bar = '2 > 1';
</script>
```

But I think this was already the case before your change. IMO we shouldn’t modify script tags, or at least only leading and trailing whitespace and consecutive line breaks.

**Comment by leofeyer** [comment]
Ok, I'll check this again.

**Comment by leofeyer** [comment]
@ausi Please check again. I have fixed the whitespace issues and I have added an external [script minifier](https://github.com/matthiasmullie/minify) to get rid of the existing bug.

**Comment by ausi** [comment]
Trailing whitespace still doesn’t get removed.

Minifying script and style tags should only be done for known types. It’s quite common to use something like `<script type="text/plain">` for inserting template or HTML code for JavaScript.

These two issues are fixed in #7927.

**Comment by leofeyer** [comment]
This is not common at all in HTML5! The `type` attribute is only required in XHTML and it not used at all in Contao.

**Comment by ausi** [comment]
> This is not common at all in HTML5!

http://stackoverflow.com/questions/13883553/what-are-modern-uses-of-script-type-text-html-and-is-this-example-cosidered-go

If the type attribute isn’t set it defaults to `text/javascript`, but if it is set to something else the browser doesn’t execute it. With the changes of my pull request `<script>` and `<script type="text/javascript">` get minified, but `<script type="text/html">` doesn’t, which is important IMO.

**Comment by leofeyer** [comment]
This is an edge case IMHO.

**Comment by leofeyer** [comment]
I have added the trailing space removal in ec4750adeb5bb0193dd0b6b1de3e70e1d98b065f. The rest is subject to discussion :)

**Comment by ausi** [comment]
> This is an edge case IMHO.

I saw that very often on the web, see also <http://stackoverflow.com/questions/4912586/explanation-of-script-type-text-template-script>.

I’m also using it myself in a Contao extension.

**Comment by leofeyer** [comment]
Can you elaborate on your use case?

**Comment by ausi** [comment]
Yes. I’m using it to get slides of a slider into the markup without loading the `<img>`s and other resources until they are needed. E.g.:

```html
<div id="my-slider">
	<img src="image1.jpg">
	<script type="text/html">
		<img src="image2.jpg">
	</script>
</div>
<script>slider('#my-slider')</script>
```

The second image doesn’t get loaded by the browser until the JavaScript wants it to.

**Comment by discordier** [comment]
@ausi is right about the script usages. Web GL shaders are also in script tags.

**Comment by leofeyer** [comment]
Ok, I'll merge the PR then.

**Comment by fritzmg** [comment]
Btw. doesn't this constitute a BC break and would therefore only be suitable for Contao 4? Some people might have relied on the aggressive minifying and now their inline navigations and pagination might look different (additional spaces) after an Update to Contao 3.5.2.

**Comment by bekanntmacher** [comment]
Diese weniger scharfe Komprimierung führt zu Problemen. Solche Formatierungen sind nicht mehr möglich. Wegen den Leerzeichen zwischen den li's wird nach dem 3-ten li umgebrochen.

```
  li {
    width: 25%;
    display: inline-block;
    vertical-align: top;
    margin-bottom: $gap-vertical-s/2;
    padding-left: 0;
  }
```

**Comment by ausi** [comment]
Die Minifizierung soll die Funktion des HTML-Codes nicht verändern, demnach sollte der CSS-Code den selben Effekt haben mit und ohne HTML-Minifizierung. Folgender CSS-Code könnte in deinem Fall das Problem eventuell beheben:

```css
ul {
  letter-spacing: -0.3em;
}
li {
  letter-spacing: normal;
  width: 25%;
  display: inline-block;
  vertical-align: top;
  margin-bottom: $gap-vertical-s/2;
  padding-left: 0;
}
```

**Comment by fritzmg** [comment]
Oder alternativ
```css
ul {
    font-size:0;
}

li {
    font-size:…;
    …
}
```
Hat natürlich den Nachteil, dass man manuell die `font-size` restoren muss.

**Comment by bekanntmacher** [comment]
@ausi ist so, danke!
