### ISSUE TITLE
do not print any html-tags if custom sections are empty

### ISSUE THREAD

**Issue by frontendschlampe** [contao/core#7742]
If the default sections are empty (no article, module or other content is delivered) there will be no output in html code in frontend for this layout section - the section does not exist in frontend.

For custom sections there is another functionality: it's all the same if there's content or not there will be an output in frontend:

```html
<div class="custom">
  <div id="test">
    <div class="inside">
    </div>
  </div>
</div>
```

So please unify the functionality for custom sections like it is for the default sections and hide them, if they're empty.

**Comment by frontendschlampe** [comment]
btw. you can reproduce this in online demo ;-)

- add a custom section to a layout
- do not add any content to section
- the html code from my first comment will be shown

**Comment by frontendschlampe** [comment]
hmmm ... I think, this is a bug and an inconsistent implementation of layout section and not a feature, isn't it?

**Comment by leofeyer** [comment]
It changes the markup and is thus not backwards compatible -> next major version.

**Comment by leofeyer** [comment]
Hm, I actually cannot reproduce this. Is it possible that it has been fixed in Contao 3.4?

**Comment by frontendschlampe** [comment]
no - it's not fixed, but you have to add the module "article" to the custom section in "Front end modules" - I tried minutes ago in the online demo

**Comment by leofeyer** [comment]
But if I add the article module, the section is no longer empty, is it?

**Comment by frontendschlampe** [comment]
No - the section is empty, because there's no content added.

**Comment by leofeyer** [comment]
Changed in 06c2db28d50584ababb3aa210652144c1d44e4df.

**Comment by frontendschlampe** [comment]
hmmm - why is the commit hash not linked? ;-)

**Comment by Toflar** [comment]
B/C he did not push yet. It will be as soon as he does :)

**Comment by leofeyer** [comment]
Sorry, I forgot the `contao/core-bundle@` prefix :)

**Comment by aschempp** [comment]
This does not really work when adding the sections manually to the template using `$this->section('foobar')`. I assume we should adjust the sections template to fix that.
