### ISSUE TITLE
Image::getHtml(null, ...) throws exception

### ISSUE THREAD

**Issue by dmolineus** [contao/core#8112]
Sometimes the Image::getHtml() methods get called with an empty src attribute (file got deleted, \Image::get() failed because of broken image, ....).

The current implementation would assume a theme image when, so that [this](https://github.com/contao/core/blob/master/system/modules/core/library/Contao/Image.php#L833) check will always be true.

Adding a simple check for an empty src right at the beginning would prevent this behaviour. I know that the src param should be checked before. Unfortunately there is a lot of 3rd party code out there which doesn't. Furthermore the assumption that an empty src param is in the themes folder is still wrong.

Typically implementations which could raise this error:

```php
echo \Image::getHtml(
    \Image::get('image/which/does/not/exist/or/could/not/be/resized.jpg', ...),
    ...
);

$fileModel = \FilesModel::findByUuid('an-uuid-of-a-file-which-does-not-exist-anymore');
echo \Image::getHtml(
    $fileModel->path,
    ...
);
```

**Comment by leofeyer** [comment]
@ausi What do you think?

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by ausi** [comment]
In my test it didn’t create a fatal error but threw an exception with the message `Directory "system/themes/flexible/images/" is not a file`. 

We could change the check to:

```php
if (!file_exists(TL_ROOT .'/'. $src) || !is_file(TL_ROOT .'/'. $src))
```

**Comment by dmolineus** [comment]
Yes, I meant exception instead of a fatal error. Changed the title. As this method is often used in the view context I prefer a silent failing.

Adding a simple condition at the beginning would solve it:

```php
if (!$src) {
    return '';
}
```

**Comment by leofeyer** [comment]
> We could change the check to:
>
> ```php
> if (!file_exists(TL_ROOT .'/'. $src) || !is_file(TL_ROOT .'/'. $src))
> ```

I think this can be simplified to `!is_file(TL_ROOT .'/'. $src)`, right?

**Comment by ausi** [comment]
> I think this can be simplified to `!is_file(TL_ROOT .'/'. $src)`, right?

Yes, I think so.

**Comment by leofeyer** [comment]
@ausi What about @dmolineus' suggestion?

```
if (!$src) {
    return '';
}
```

**Comment by ausi** [comment]
An empty source would already be caught by the `is_file` check, so we don’t need the extra check IMO.

**Comment by dmolineus** [comment]
No, an empty source get's the theme directory and is not empty anymore.

**Comment by ausi** [comment]
And the theme directory would not pass the suggested `is_file(TL_ROOT .'/'. $src)` check because it’s a directory and not a file.

**Comment by leofeyer** [comment]
Yes, but why go through the theme path conversion if we already know that an empty source will lead to an empty return value?

**Comment by leofeyer** [comment]
Fixed in 3376781fb4f46e01693862d235f1ce7a273f4bed. I went with the `$src != '') solution, because this way we can keep the `file_exists()` check, which works with files and symlinks. Otherwise we would have had to check for `is_file() || is_link()`.

**Comment by ausi** [comment]
But this way `\Image::getHtml('files/')` would still throw an exception?

**Comment by leofeyer** [comment]
Changed in 0ba305a5e1d518338f48d032c5e73a11654cbd2f.
