### ISSUE TITLE
file-naming / autorenaming issues in the file-manager 

### ISSUE THREAD

**Issue by asaage** [contao/core#8295]
the 3.5.8 Version (and probably older versions too) strip the first charakter of the filename on upload in case of äöü..
it's not reproduceable in the online-demo due to fileupload resrictions.

following szenario:
sourc-file `Änderungsantrag.pdf`
destination-file (upload in contao 3.3.3) becomes `Aenderungsantrag.pdf` and shows up as `Aenderungsantrag.pdf`

compared to 3.5.8 where the behavior differs and seems to be a little messed up.
sourc-file `Änderungsantrag.pdf`
destination-file (upload in contao 3.5.8) will be saved as `Änderungsantrag.pdf`
but shows up as 
`nderungsantrag.pdf` + **renaming this file is now impossible**.

still 3.5.8:
uploading `Büro.png` will be saved as `Büro.png` and shows up as `Büro.png` :+1:
but renaming it to `Büro_foo.png` results in  `Buero_foo.png`

i would consider this as 3 bugs
- missing first letter
- impossible renaming
- inconsistent naming routines

(i personaly would like to be able to use every character that has no special meaning to the underlying sytem / file-system like linux/windows)

**Comment by asaage** [comment]
What would be an appropriate way to confirm this?

**Comment by fenepedia** [comment]
I could confirm, that there is a rename problem. But I could rename the files

![names](https://cloud.githubusercontent.com/assets/566448/14321465/9d347534-fc19-11e5-8340-6365347fb4a8.jpg)

**Comment by Aybee** [comment]
I can confirm the first post in 3.5.9 on Windows 10.

**Comment by asaage** [comment]
some more test's...
unfortunately i do not have equal versions on different systems at this point

3.5.6 on win IIS
works more or less (missing Thumbnail is a serverconfig issue with umlaute)
![image](https://cloud.githubusercontent.com/assets/4138336/14323493/19169298-fc21-11e5-9416-165cd2a143f4.png)
renaming to Änderung2 results in
![image](https://cloud.githubusercontent.com/assets/4138336/14323619/7f48c2b6-fc21-11e5-81e4-5c1e3664cf25.png)

3.5.8 on Ubuntu Apache
![image](https://cloud.githubusercontent.com/assets/4138336/14323659/abbc6d48-fc21-11e5-957e-5d6ae1e81357.png)
rename wont save
![image](https://cloud.githubusercontent.com/assets/4138336/14323698/e1ca5724-fc21-11e5-9a3e-7a6334fd8c77.png)

3.3.3 on Ubuntu Apache
![image](https://cloud.githubusercontent.com/assets/4138336/14323784/3eba1e74-fc22-11e5-890d-a29702b8e382.png)
![image](https://cloud.githubusercontent.com/assets/4138336/14323806/60dd6bf0-fc22-11e5-9ab9-720bf697ec90.png)

**Comment by thomaspahl** [comment]
Test on 3.5.9 on Lubuntu 15.10, en_US.utf8, Apache 2.4 with LANG=C, PHP mbstring, client Window 7 Firefox/IE11:
I can confirm the symptom of the dropped initial umlaut (ß as well).After upload, the filename is left-truncated, but I can download the file (via the symbol in front) with the correct name!

The database ``tl_files`` entry shows inconsistent values: in column ``path`` the full path including filename contains the original filename, however, the column ``name`` contain the incorrect filename (without leading umlaut). You can see this discrepancy in the filemanager screen when hovering over the pencil icon: the link displayed contains the correct full path - same on the edit page after you click on the pencil.

If I correct the name in the database and reload the file manager page, the initial umlaut is dropped from the display again. Also, any attempt to edit the name in the filemanager edit page fails, the database entry remains unchanged (the manually inserted leading umlaut is kept).

Selecting the file in a download element results in a wrong filename display and a successful download with a wrong filename.

**Comment by thomaspahl** [comment]
One more test:
* create a file "ü-test.pdf" outside Contao (by ftp, e.g.)
* open that directory in filemanager
* filename ist displayed as "-test.pdf", full path is ok. No database entry yet
* click on info icon -> database entry is created with name="-test.pdf"

So it is not only an upload issue.

**Comment by asaage** [comment]
i wonder what @fenepedia did...
can you tell some system details?

**Comment by fenepedia** [comment]
Hmm I think @leofeyer could answer this question better than me. My Server ist hosted and configured by him.

**Comment by leofeyer** [comment]
@contao/developers /cc

**Comment by thomaspahl** [comment]
For one test case, download (see my prior comment), I drilled the issue down to a problem with the PHP ``pathinfo()`` function used in ``Files::__get()``. ``pathinfo()`` drops the first character if is an UTF8 umlaut (probably any non-ASCII7) and the system environment has LANG=C (which is in the default environment of my apache2.4 and obviously a few webservers). PHP versions 5.6.11 and 5.4

You can easily verify it by inserting
```
<?php var_dump(pathinfo('/home/test/ü-ütest-pdf')); ?>
```
into ``ce_download.html5`` and then using any download link.

It can also be reproduced on the command line:
```
http@odin:~$ echo $LANG
en_US.utf8
http@odin:~$ cat x.php
<?php
var_dump(pathinfo('/home/test/ü-ütest.pdf'));
http@odin:~$ php x.php
array(4) {
  ["dirname"]=>
  string(10) "/home/test"
  ["basename"]=>
  string(13) "ü-ütest.pdf"
  ["extension"]=>
  string(3) "pdf"
  ["filename"]=>
  string(9) "ü-ütest"
}
http@odin:~$ LANG=C php x.php
array(4) {
  ["dirname"]=>
  string(10) "/home/test"
  ["basename"]=>
  string(11) "-ütest.pdf"
  ["extension"]=>
  string(3) "pdf"
  ["filename"]=>
  string(7) "-ütest"
}
```

A hot fix in ``File.php`` around line 160ff just for this case is
```
	/**
	 *  TEMP.FIX for pathinfo() locale C issue
	 */
	private static function mypathinfo($strPath)
	{
			$oldlocale = setlocale(LC_CTYPE, "0");
			if (stripos($oldlocale, '.utf8'))
			{
				$arr = pathinfo($strPath);
			}
			else
			{
				setlocale(LC_CTYPE, 'en_US.utf8');
				$arr = pathinfo($strPath);
				setlocale(LC_CTYPE, oldlocale);
			}
			return $arr;
	}
	
	/**
	 * Return an object property
...
	*/
	public function __get($strKey)
	{
		switch ($strKey)
		{
...
			case 'name':
			case 'basename':
				if (!isset($this->arrPathinfo[$strKey]))
				{
==>					$this->arrPathinfo = static::mypathinfo(TL_ROOT . '/' . $this->strFile);
				}
				return $this->arrPathinfo['basename'];
				break;
```

This rough fix also covers the file upload case.
But I found quite a number of ``pathinfo()`` calls in the ``system/modules/core`` tree, plus more calls to ``basename()`` (which has the same problem). So a better solution is needed.

**Comment by thomaspahl** [comment]
As a brute-force approach, just inserting
```
setlocale(LC_CTYPE, 'en_US.utf8');
```
into ``initconfig.php`` without any other change seems to fix the issue, including the filemanager display and rename (rename then changes 'ü' to 'ue' etc - which I do not like at all).
I do not now if this patch has any negative effects elsewhere (sorting, case folding, ...).

**Comment by leofeyer** [comment]
Seems we have to use a library or copy the `mb_pathinfo()` function e.g. from here:

http://core.wp-a2z.org/oik_api/phpmailermb_pathinfo/

**Comment by thomaspahl** [comment]
http://php.net/manual/en/function.pathinfo.php says (RTFM helps once more):
>    Note:
>
>   pathinfo() is locale aware, so for it to parse a path containing multibyte characters correctly, the matching locale must be set using the setlocale() function.

So it seems that locale switching is the right way (it is already used in some vendor code with LC_NUMERIC). In my tests, setting LC_CTYPE was sufficient (and probably less overhead than LC_ALL), and only the charset (utf8) should be relevant.

A  solution without changing core code is redefining `pathinfo` and `basename`  within the Contao namespace. Works fine for me in php 5.6 + 5.4 installations.
``` php
namespace Contao;

function pathinfo($path, $option=null)
{
	$locale = setlocale(LC_CTYPE, '0');
	setlocale(LC_CTYPE, 'en_US.utf8');
	$arr = is_null($option) ? \pathinfo($path) : \pathinfo($path, $option);
	setlocale(LC_CTYPE, $locale);
	return $arr;
}
function basename($path, $suffix=null)
{
	$locale = setlocale(LC_CTYPE, '0');
	setlocale(LC_CTYPE, 'en_US.utf8');
	$arr = \basename($path, $suffix);
	setlocale(LC_CTYPE, $locale);
	return $arr;
}
```
Namespaces are made for such things...
Extensions are not covered, but I think it would be valid as a core bug fix in 3.5.10

**Comment by asaage** [comment]
:+1: sounds promising...
can the same be achived with setting
```intl.default_locale``` in the php.ini to an appropiate value?
i am a little bit concerned about "Extensions are not covered..."

**Comment by aschempp** [comment]
Using `setlocale` is dangerous. The manual at http://php.net/manual/en/function.setlocale.php says

> **Warning** The locale information is maintained per process, not per thread. If you are running PHP on a multithreaded server API like IIS, HHVM or Apache on Windows, you may experience sudden changes in locale settings while a script is running, though the script itself never called `setlocale()`. This happens due to other scripts running in different threads of the same process at the same time, changing the process-wide locale using `setlocale()`.

**Comment by leofeyer** [comment]
I second @aschempp's concerns, therefore I'd prefer to add a `String::pathinfo()` method and use the [PHPMailer mb_pathinfo](https://github.com/PHPMailer/PHPMailer/blob/master/class.phpmailer.php#L3520-L3554) code there.

**Comment by Toflar** [comment]
Sounds like it should rather go to `File`, no?

**Comment by leofeyer** [comment]
Also, this seems to be a very common problem. There are over 38,000 code snippets when searching for mb_pathinfo on Github: https://github.com/search?q=mb_pathinfo&type=Code&utf8=%E2%9C%93

**Comment by leofeyer** [comment]
Fixed in 2276fa8ad17f65eccbc7a17edc03cb13d98320f0  and a0bf86b82b98079c209a23f74bfdd9091dfcfb0e.

**Comment by asaage** [comment]
Would you reopen this? its not completely fixed. (3.5.12)
i created following 0Byte testfiles on my desktop:
![image](https://cloud.githubusercontent.com/assets/4138336/15427729/51fbfd94-1e97-11e6-8c07-4c05f9575c10.png)
and uploaded them via dropzone
the result in the file-view:
![image](https://cloud.githubusercontent.com/assets/4138336/15427775/97b0b190-1e97-11e6-8b90-4f23c9882241.png)
though in the file-edit view names and paths as well as the renaming-function are more or less okay
![image](https://cloud.githubusercontent.com/assets/4138336/15427837/04f96cf6-1e98-11e6-95de-71fd52502c49.png)
I wonder why it should be possible to upload something named Ö.. but not to rename something to Ö..

**Comment by leofeyer** [comment]
> I wonder why it should be possible to upload something named Ö.. but not to rename something to Ö..

?

**Comment by asaage** [comment]
forget about the last sentence - sometimes i wonder a lot...
just take a look at this:
![](https://cloud.githubusercontent.com/assets/4138336/15427775/97b0b190-1e97-11e6-8b90-4f23c9882241.png)
especially the last three files which seem to be the same - but they are not.

**Comment by leofeyer** [comment]
How exactly do I reproduce the issue?

**Comment by fritzmg** [comment]
I encountered the following under Windows:

If I put a file called `Ö_test.txt` into the files directory (not using the file uploader) and then go into the file manager, it will be displayed as follows:

![o_test_1](https://cloud.githubusercontent.com/assets/4970961/15984850/0919efe2-2fda-11e6-845c-f560001d5f61.png)

When I do a dabfs sync afterwards, it will say

![o_test_2](https://cloud.githubusercontent.com/assets/4970961/15984853/19e5ac08-2fda-11e6-9768-b85f44f56d99.png)

When I then upload another file named exactly the same (`Ö_test.txt`) using the file manager, it will display both:

![o_test_3](https://cloud.githubusercontent.com/assets/4970961/15984859/2fce8aa8-2fda-11e6-9427-4c4bdc4ffd4e.png)

This is the state of the database afterwards:

![o_test_4](https://cloud.githubusercontent.com/assets/4970961/15984861/3712effc-2fda-11e6-918a-1e37f2e2a09d.png)

**Comment by fritzmg** [comment]
I can reproduce @asaage 's problem under Linux:

If I put a file called `Ö_test.txt` into the files directory (not using the file uploader) and then go into the file manager, it will be displayed as follows:

![o_test_5](https://cloud.githubusercontent.com/assets/4970961/15984874/93bae19c-2fda-11e6-8121-5fdafb2993dc.png)

When I do a Dbafs sync afterwards, it will say 

![o_test_6](https://cloud.githubusercontent.com/assets/4970961/15984907/46cf024a-2fdb-11e6-8bb1-9d27682fc993.png)

When I edit the file, it will display the name normally:

![o_test_7](https://cloud.githubusercontent.com/assets/4970961/15984913/6c396eee-2fdb-11e6-96f1-b78b5044eabf.png)

**Comment by leofeyer** [comment]
I cannot reproduce the issue on Mac OS X, which is why I'm struggling to fix it. Anyone else?

@contao/developers /cc

**Comment by fritzmg** [comment]
The problem with Windows is the following: http://stackoverflow.com/questions/15055192/why-does-windows-need-to-utf8-decode-filenames-for-file-get-contents-to-work

It's quite a bitch ;). I stumbled upon this in an extension of mine, but I could never solve it directly (in my case the file paths are now `rawurlencode`d and then decoded - the extension transfers files from one Contao installation to another, among other thigns).

**Comment by asaage** [comment]
the db entry ```tl_files.name``` is correct if i use the uploader
the edit/text/input is also ok
only in the file-three the first character is missing - maybe you are using different methods to output those strings.

btw i'm on Linux.

i did not check how that behaves if i put the file via ftp and sync afterwards.

**Comment by asaage** [comment]
#2508

**Comment by leofeyer** [comment]
I was able to reproduce the issue on Linux, however I'm not sure what to do now. In contrast to the initial problem description, I did not have a problem renaming the file in Contao 3.5.25.

**Comment by asaage** [comment]
Renaming as well as displaying the first character is working flawlessly since at least 3.5.17.
If there are no intensions to apply the same naming rules on upload's like on edit's (which i would prefer) this can probably be closed.

**Comment by leofeyer** [comment]
Since we are removing those rules in Contao 4.4 entirely (see contao/core-bundle@0c0b3d89f2109e12ea80a837ce3ec36bf00a629b), I'm closing the issue.
