### ISSUE TITLE
changing the content of a page leads to multiple search results for the same page

### ISSUE THREAD

**Issue by fritzmg** [contao/core#8439]
## Reproduction

* log into http://demo.contao.org/contao
* go to _System_ » _Maintenance_ and purge the search cache
* edit the content elements of the "Home" article of the "Home" page
* [edit the first text content element](http://demo.contao.org/contao/main.php?do=article&table=tl_content&act=edit&id=1) and append "Lorem ipsum." for example an save
* open http://demo.contao.org/en/ in the frontend
* go to http://demo.contao.org/en/search.html and [search for "Lorem"](http://demo.contao.org/en/search.html?keywords=Lorem&query_type=and)
* there will be one result (the "Home" page)
* edit the first text content element again and append "Lorem ipsum dolor sit amet." (so that it says "Lorem ipsum. Lorem ipsum dolor sit amet.") and save
* open http://demo.contao.org/en/ in the frontend
* go to http://demo.contao.org/en/search.html and [search for "Lorem"](http://demo.contao.org/en/search.html?keywords=Lorem&query_type=and)
* there will be __two__ results, each pointing to the "Home" page

The first result will have [100% relevance] and shows the most recent edit:
> end users can only log in to the front end. Lorem ipsum. Lorem ipsum dolor sit amet. Learn

The second result will have [50% relevance] and shows the initial edit:
> end users can only log in to the front end. Lorem ipsum. Learn more On the following pages you

* go to _System_ » _Maintenance_ and purge the search cache again
* open http://demo.contao.org/en/ in the frontend
* go to http://demo.contao.org/en/search.html and [search for "Lorem"](http://demo.contao.org/en/search.html?keywords=Lorem&query_type=and)
* there will only be one search result now, as expected

## Cause

`\Contao\Search::indexPage` searches for existing entries [here](https://github.com/contao/core/blob/3.5.15/system/modules/core/library/Contao/Search.php#L180), using the checksum of the page's content, and then either creates a new entry or updates the existing one.
```php
$objIndex = $objDatabase->prepare("SELECT id, url FROM tl_search WHERE checksum=? AND pid=?")
						->limit(1)
						->execute($arrSet['checksum'], $arrSet['pid']);

// Add the page to the tl_search table
if ($objIndex->numRows)
{
	// update existing entry …
}
else
{
	// create new entry …
}
```
However, since the content has changed, the checksum is different of course, thus after an edit of a page, there will always be a new entry in `tl_search` - which leads to multiple search results for the same page.

## Fix?

Shouldn't old entries with the same `url` simply be deleted or updated, instead of searching for the checksum? Under what circumstances would an entry get updated with new values? If the page has changed, the checksum will be different. If a page did not change, there is nothing to be updated in the first place, I assume.

**Comment by leofeyer** [comment]
Should be fixed in fccd6822adb8177209b37a41af3b042f70442ea9. Please test and confirm.

**Comment by fritzmg** [comment]
Side note: this problem still exists, if you change the content of a page and then open it in the frontend under a different URL (e.g. example.org/ vs example.org/index.html, see also #8460). Though I guess technically that works as expected since a different URL means different content as well (from a client's perspective).
